/* rq_dmy_cache is generated from this code. This code should not be included in rq. */
/* Output should be redirected to "rq_date_cache_initialisation.h" */
#include <stdio.h>
#include "rq_date.h"

static void date_to_dmy(rq_date julian,  short *day, short *mon, short *year)
{
    int l = julian + 68569;
    int n = 4 * l / 146097;
    int it;
    l = l - (146097 * n + 3) / 4;
    it = 4000 * (l + 1) / 1461001;
    l = l - 1461 * it / 4 + 31;
    *mon = 80 * l / 2447;
    *day = l - 2447 * (*mon) / 80;
    l = (*mon) / 11;
    *mon = (*mon) + 2 - 12 * l;
    *year = 100 * (n - 49) + it + l;
}

main()
{
    rq_date j;

    printf("/* This is initialisation for rq_dmy_cache, generated by rq_date_cache_generator.c */\n");
    for(j = RQ_DMY_CACHE_START; j < RQ_DMY_CACHE_START + RQ_DMY_CACHE_SIZE; j++)
    {
        short day, mon, year;
        date_to_dmy(j, &day, &mon, &year);
        if(j % 32 == 0)
            printf("\n");
        printf("{%d,%d,%d}, ", year, mon, day);
    }
    return 0;
}
